
spring.application.name=farmkart

spring.datasource.url=jdbc:postgresql://ep-cold-sunset-a1mm5g7i-pooler.ap-southeast-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_eYrIR1DJU4jn

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}

# JWT
jwt.secret=mangostore_super_secret_key_2024_production_ready_256bits_long_key
jwt.expiration=86400000

# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# CORS
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000,https://farmkart-pi.vercel.app/

Admin credentials (change in production!)
app.admin.username=Siva
app.admin.password=sivadevireddy


# Razorpay credentials ? get from https://dashboard.razorpay.com/app/keys
# Use TEST keys during development, LIVE keys in production

razorpay.key.id=rzp_test_SYZnw2HGsYSkUU
razorpay.key.secret=HZl3dQtWvKVdx6OcYUMEnDPv